# Generated by Django 3.0.14 on 2021-04-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suject',
            new_name='Subject',
        ),
    ]
